### ISSUE TITLE
Noob question: how is it more useful than java.util.zip?

### ISSUE THREAD

**Issue by seinecle** [helpermethod/zip-forge#46]
The title of the issue is the question. Can you please explain? Thanks!

**Comment by helpermethod** [comment]
Hi @seinecle!

Good question! Feature-wise, they are actually quite similar.
But ZIP Forge has a few distinct features:

* Less boilerplate: ZIP Forge is basically a thin wrapper/DSL around Java's own ZIP facilities and offers a higher-level API which is more declarative in nature.
* It can deal with very large files due to its use of java.nio.file.FileSystem, which java.util.zip can't handle.
* The tree-like structure of the DSL mimics the structure of the ZIP file. All paths are relative to the corresponding parent directory. with java.util.zip, you always need to provide the full path when adding files to directories
* Small API: The API is very limited, which is actually a feature. It just solves a distinct use case, which is ad-hoc creation of ZIP files. No big API to learn.

I've basically created the library for two reasons:
* to create ad-hoc ZIP files in tests, without much boilerplate
* to see how compact such a DSL could be

Hope that answers your questions!

**Comment by seinecle** [comment]
Very clear thank you! DSL has other meanings and that can confused me I guess.
